#https://github.com/mpv-player/mpv/blob/master/etc/mpv.conf

# Enable osd and display
osd-level=0

# Disable Stock OSC for ModernZ skin
osc=no
title-bar=no

# No window title bar
border=no

# Save window position and size on quit
save-position-on-quit=yes

# Video starts at the beginning by default
save-position-on-quit=no

# Optionally keep the player open after a video ends to maintain the window
keep-open=yes

# force starting with centered window
geometry=50%:50%

# Enable hardware decoding if available.
hwdec=auto

# Maximum player size inside the screen
autofit-larger=80%x100%

# Specify fast video rendering preset (for --vo=<gpu|gpu-next> only)
# Recommended for mobile devices or older hardware with limited processing power
profile=fast




